Add SHM in vm server
nuta/resea pull request #43
Opened 2020-12-03 15:35 UTC by arpitvaghela

This PR proposes implementation of Shared Memory based on #28 . 

The `readtest()` in [`shm_test.c`](https://github.com/yashrajkakkad/resea/blob/shm_vm/servers/apps/test/shm_test.c) requires `shm_test_server` to be started causing integration tests to fail. Is there a way to check on `shm_test_server` ?

2020-12-05 11:44 UTC, nuta commented
> The readtest() in shm_test.c requires shm_test_server to be started causing integration tests to fail. Is there a way to check on shm_test_server ?

It's not your fault. That's because `shm_test` is not enabled in the kernel configs in `ci`. I'll work on some improvements for this problem and let you know once I've done.

2020-12-05 11:45 UTC, nuta requested changes
Thank you for the PR! Could you take a look at my review comments?

2020-12-05 11:45 UTC, nuta commented on interface.idl
> -
Nit: Don't remove blank line between `namespace`s.

2020-12-05 11:45 UTC, nuta commented on interface.idl
> +namespace shm_test {
Nit: Add a blank line after `}`.

2020-12-05 11:45 UTC, nuta commented on interface.idl
> +}
Nit: Add a blank line after `}`.

2020-12-05 11:45 UTC, nuta commented on interface.idl
> +    rpc map(shm_id : int, flag:int)   ->  (vaddr : vaddr);
Please fix whitespaces: e.g., this line should be `(shm_id: int, flag: int) -> (vaddr: vaddr);`

2020-12-05 11:45 UTC, nuta commented on servers/apps/test/shm_test.c
> +
Ditto: missing `(void)` and inconsistent blank lines.

2020-12-05 11:45 UTC, nuta commented on servers/apps/test/shm_test.c
> +void test() {
Nit: Missing `(void)`.

2020-12-05 11:45 UTC, nuta commented on servers/apps/test/shm_test.c
> +    }
Nit: Add a newline at EOF. Please install editorconfig on your editor to automatically insert it.

2020-12-05 11:45 UTC, nuta commented on servers/shm_test/build.mk
> +objs-y := main.o
Ditto: missing a newline at EOF

2020-12-05 11:45 UTC, nuta commented on servers/shm_test/main.c
> +
nit: remove

2020-12-05 11:45 UTC, nuta commented on servers/shm_test/main.c
> +
ditto

2020-12-05 11:45 UTC, nuta commented on servers/shm_test/main.c
> +    //    write to vaddr
Nit: Remove redundant whitespaces before the setence.

2020-12-05 11:45 UTC, nuta commented on servers/vm/main.c
> +
ditto

2020-12-05 11:45 UTC, nuta commented on servers/vm/main.c
> +                int flag = (m.shm_map.flag)?MAP_W:0;
Nit: Inconsistent whitespaces. This line should be `(...) ? MAP_W : 0`

2020-12-05 11:45 UTC, nuta commented on interface.idl
> +    rpc map(shm_id : int, flag:int)   ->  (vaddr : vaddr);
In this patch, `flag` indicates whether the mapped area is writable, right? If so, let's rename this field to `writable: bool`.

2020-12-05 11:45 UTC, nuta commented on servers/shm_test/main.c
> +int main() {
Nit: A return value from `main` have no not meaning on Resea. This line should be `void main(void)`.

2020-12-05 11:45 UTC, nuta commented on servers/apps/test/shm_test.c
> +#define MSG "hello task b"
`MSG` is a bit confusing name. How about `TEST_DATA`?

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +int shm_check_available() {
ditto:  `()` -> `(void)`

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +    for (; i < NUM_SHARED_MEMS_MAX; i++) {
Nit: you think you can declare `i` in the `for` statement.

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +int shm_close(int shm_id) {
ditto: missing a blank line after `}`

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.h
> +#endif
ditto: missing a newline at EOF

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.h
> +static struct shm_t shared_mems[NUM_SHARED_MEMS_MAX];
Nit: please avoid declaring `static` variables in a header file. I guess this line should be in `shm.c`.

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +        bzero(&shared_mems[i], sizeof(struct shm_t));
Just reset the `inuse` field.  I think we don't need to fill all fields with zeros.

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.h
> +struct shm_t {
This should be `struct shm`. `_t` suffix is for `typedef`-ed types.

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +}
ditto: missing a blank line after `}`

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +struct shm_t* shm_stat(int shm_id) {
In Resea, we use `*_lookup` for functions that takes an ID and returns a pointer to the associated struct. Please rename this function to `shm_lookup`.

2020-12-05 11:45 UTC, nuta commented on servers/vm/shm.c
> +}
I guess we don't need function: use `shm_stat`.

2020-12-05 11:45 UTC, nuta commented on servers/vm/main.c
> +                int shm_id = shm_create(m.shm_create.size, paddr,slot);
Let's merge these lines into `shm_create` as possible.

2020-12-05 11:45 UTC, nuta commented on servers/vm/main.c
> +                }
These lines should be implemented in a separate function in `shm.c`.

2020-12-05 11:45 UTC, nuta commented on servers/apps/test/shm_test.c
> +    // create shared memory
Nit: In Resea, comments should be `// A sentence.` for consistency. For example: `// Create a shared memory.`.

2020-12-05 11:45 UTC, nuta commented on servers/apps/test/shm_test.c
> +    readtest();
Nit: These function names sound a bit vague. Do you have any ideas?

2020-12-05 11:45 UTC, nuta commented on servers/shm_test/main.c
> +                break;
Use `discard_unknown_message` to handle unsupported messages:
```c
            default:
                discard_unknown_message(&m);
```

2020-12-05 17:46 UTC, nuta commented
> > The readtest() in shm_test.c requires shm_test_server to be started causing integration tests to fail. Is there a way to check on shm_test_server ?
> 
> It's not your fault. That's because `shm_test` is not enabled in the kernel configs in `ci`. I'll work on some improvements for this problem and let you know once I've done.

I added a support for using config fragments. Please add `CONFIG_SHM_TEST_SERVER=y` to failing test configs (in `ci` directory).

2020-12-24 10:22 UTC, nuta commented
JFYI: If you think this PR is ready, please let me know using "Re-request review" on GItHub.

2020-12-26 08:30 UTC, arpitvaghela commented
@nuta  Can you please review the [last commmit](https://github.com/nuta/resea/pull/43/commits/70cbed567567e3ac78bd31f3723716626e2ab17b). Got this Exception in integration test
`[vm] WARN: alloc_phy_pages: unaligned paddr 0000000001000100`
Not sure how to solve.

2020-12-29 14:10 UTC, nuta requested changes
I guess that bug could be resolved by this change.

2020-12-29 14:10 UTC, nuta commented on servers/vm/shm.c
> +    paddr_t paddr;
`paddr` should be initialized with zero. `alloc_phy_pages` allows specifying the physical memory page to be mapped if paddr is not zero.
```
paddr_t paddr = 0;
```

2020-12-31 10:17 UTC, nuta reviewed
Looks Good 👍 Could you fix conflicts so that I can merge your PR?

2021-01-04 09:59 UTC, nuta requested changes
Hi, I noticed that arm64 tests are failing. Could you fix this part?

2021-01-04 09:59 UTC, nuta commented on servers/vm/shm.c
> +    int flag = (writable) ? MAP_TYPE_READWRITE : 0;
```
int flag = (writable) ? MAP_TYPE_READWRITE : 0;
```

Please use `MAP_TYPE_READONLY` instead of `0` to fix failing CI tests on arm64.

2021-01-05 11:23 UTC, nuta approved these changes

2021-01-05 11:23 UTC, merged

2021-01-05 11:28 UTC, nuta commented
Thanks a lot for your work, @arpitvaghela! I plan to implement a Wayland-compatible GUI server in Q1 and your contribution will be a key part for rendering pixels!

2021-01-05 11:52 UTC, arpitvaghela commented
You've been of great help. :relaxed: